apiVersion: v1
kind: List
items:
  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: jenkins-edit
      namespace: datacenter-a
    roleRef:
      name: edit
    subjects:
      - kind: ServiceAccount
        name: jenkins
        namespace: ci
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: infra-int-testing-app-pipeline
    spec:
      source:
        git:
          uri: https://github.com/rh-ei-stp/infrastructure-cicd.git
          ref: master
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
        runPolicy: Parallel